app_container_name: "{{ app_name }}-app"
db_container_name: "{{ app_name }}-db"
app_image_name: "{{ app_name }}-php"
app_root: "/srv/apps/{{ app_name }}"
edge_gateway_base_path: "/opt/edge-gateway"
edge_gateway_network: "edge-net"
app_network: "app_net"
app_enable_edge_auth: false
