---
# ============================================================
# WIREGUARD VPN (SERVER)
# ============================================================

- name: Deploy WireGuard Server
  hosts: wireguard_servers
  become: true
  vars_files:
    - "../group_vars/all/vault.yml"

  roles:
    - role: wireguard
